# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
c1 = City.create({description: "Region Metropolitana"})

m1 = Municipality.create({description: "Santiago"})
m2 = Municipality.create({description: "Cerrillos"})
m3 = Municipality.create({description: "Cerro Navia"})
m4 = Municipality.create({description: "Conchalí"})
m5 = Municipality.create({description: "El Bosque"})
m6 = Municipality.create({description: "Estacion Central"})
m7 = Municipality.create({description: "Huechuraba"})
m8 = Municipality.create({description: "Independencia"})
m9 = Municipality.create({description: "La Cisterna"})
m10 = Municipality.create({description: "La Florida"})
m11 = Municipality.create({description: "La Granja"})
m12 = Municipality.create({description: "La Pintana"})
m13 = Municipality.create({description: "La Reina"})
m14 = Municipality.create({description: "Las Condes"})
m15 = Municipality.create({description: "Lo Barnechea"})
m16 = Municipality.create({description: "Lo Espejo"})
m17 = Municipality.create({description: "Lo Prado"})
m18 = Municipality.create({description: "Macul"})
m19 = Municipality.create({description: "Maipú"})
m20 = Municipality.create({description: "Ñuñoa"})
m21 = Municipality.create({description: "Pedro Aguirre Cerda"})
m22 = Municipality.create({description: "Peñalolen"})
m23 = Municipality.create({description: "Providencia"})
m24 = Municipality.create({description: "Pudahuel"})
m25 = Municipality.create({description: "Quilicura"})
m26 = Municipality.create({description: "Quinta Normal"})
m27 = Municipality.create({description: "Recoleta"})
m28 = Municipality.create({description: "Renca"})
m29 = Municipality.create({description: "San Juaquin"})
m30 = Municipality.create({description: "San Miguel"})
m31 = Municipality.create({description: "San San Ramon"})
m32 = Municipality.create({description: "Vitacura"})

ca1 = Category.create({description: "Placa Base"})
ca2 = Category.create({description: "Monitor"})
ca3 = Category.create({description: "Tarjeta Grafica"})
ca4 = Category.create({description: "Mouse"})
ca5 = Category.create({description: "Teclado"})
ca6 = Category.create({description: "WebCam"})
ca7 = Category.create({description: "Audifonos"})
ca8 = Category.create({description: "Refrigeracion"})
ca9 = Category.create({description: "Procesador"})
ca10 = Category.create({description: "Gabinete"})
ca11 = Category.create({description: "Almacenamiento"})
ca12 = Category.create({description: "Memoria Ram"})
ca13 = Category.create({description: "juego de plataforma"})

cl1 = Classification.create({description: "altamente positiva"})
cl2 = Classification.create({description: "muy positiva"})
cl3 = Classification.create({description: "medianamente positiva"})
cl4 = Classification.create({description: "variado"})
cl5 = Classification.create({description: "critico"})
